// Jobs

export const FETCH_ALL_JOBS = "FETCH_ALL_JOBS";
export const FETCH_JOBS_SUCCESS = "FETCH_JOBS_SUCCESS"
export const FETCH_JOBS_FAILURE = "FETCH_JOBS_FAILURE"
export const FETCH_JOBS_REQUEST = 'FETCH_JOBS_REQUEST'


// login

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

// LOGOUT

export const LOGOUT = 'LOGOUT'
export const LOGOUT_FAILED = 'LOGOUT_FAILED'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

// profile

export const LOAD_PROFILE_SUCCESS = "LOAD_PROFILE_SUCCESS"

//CUSTOMERS

export const FETCHING_CUSTOMERS = "FETCHING_CUSTOMERS"

export const FETCH_CUSTOMER_SUCCESS = 'FETCH_CUSTOMER_SUCCESS'


// applications

export const FETCH_APPLICATIONS_REQUEST = 'FETCH_APPLICATIONS_REQUEST';
export const FETCH_APPLICATIONS_SUCCESS = 'FETCH_APPLICATIONS_SUCCESS';
export const FETCH_APPLICATIONS_FAILURE = 'FETCH_APPLICATIONS_FAILURE';


// applicants 
export const FETCH_APPLICANTS_REQUEST = 'FETCH_APPLICANTS_REQUEST';
export const FETCH_APPLICANTS_SUCCESS = 'FETCH_APPLICANTS_SUCCESS';
export const FETCH_APPLICANTS_FAILURE = 'FETCH_APPLICANTS_FAILURE';


// seeker applications

export const FETCH_SEEKER_APPLICATIONS_REQUEST = 'FETCH_SEEKER_APPLICATIONS_REQUEST';
export const FETCH_SEEKER_APPLICATIONS_SUCCESS = 'FETCH_SEEKER_APPLICATIONS_SUCCESS';
export const FETCH_SEEKER_APPLICATIONS_FAILURE = 'FETCH_SEEKER_APPLICATIONS_FAILURE';


// filter types

export const FILTER_ERROR = "FILTER_ERROR"
export const FILTER_SUCCESS = "FILTER_SUCCESS "
export const FILTER_REQUEST = "FILTER_REQUEST"

// EMPTY filtered jobs

export const EMPTY_FILTERED_JOBS = "EMPTY_FILTERED_JOBS"



// SIGNUP types

export const SIGNUP_FAILURE = "SIGNUP_FAILURE"
export const SIGNUP_REQUEST = "SIGNUP_REQUEST"
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"

// Applicant info types

export const FIND_INFO_REQUEST = "FIND_INFO_REQUEST"
export const FIND_INFO_SUCCESS = "FIND_INFO_SUCCESS"
export const FIND_INFO_FAILED = "FIND_INFO_FAILED"


