// Jobs

export const FETCH_ALL_JOBS = "FETCH_ALL_JOBS";
export const FETCH_JOBS_SUCCESS = "FETCH_JOBS_SUCCESS"
export const FETCH_JOBS_FAILURE = "FETCH_JOBS_FAILURE"
export const FETCH_JOBS_REQUEST = 'FETCH_JOBS_REQUEST'


// login

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

// LOGOUT

export const LOGOUT = 'LOGOUT'
export const LOGOUT_FAILED = 'LOGOUT_FAILED'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

// profile

export const LOAD_PROFILE_SUCCESS = "LOAD_PROFILE_SUCCESS"

//CUSTOMERS

export const FETCHING_CUSTOMERS = "FETCHING_CUSTOMERS"
export const FETCH_CUSTOMER_SUCCESS = 'FETCH_CUSTOMER_SUCCESS'


export const SIGNUP_FAILURE = "SIGNUP_FAILURE"
export const SIGNUP_REQUEST = "SIGNUP_REQUEST"
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"


